services:
  exporter:
    command:
      - --web.listen-address=:${COMPOSE_EXPORTER_PORT:-9219}
      - --${FEATURE_NAME}.refresh-interval=30s
      - --${FEATURE_NAME}.target=address=google.com,port=443
      - --${FEATURE_NAME}.target=address=yahoo.com,port=443
