GO_MODULE ?= github.com/zxzharmlesszxz/prometheus-ssl-exporter
FRAMEWORK_MODULE ?= github.com/zxzharmlesszxz/prometheus-exporter-framework
GO ?= go
GOFMT ?= gofmt
DOCKER ?= docker
STATICCHECK_VERSION ?= v0.8.1
STATICCHECK ?= $(GO) run honnef.co/go/tools/cmd/staticcheck@$(STATICCHECK_VERSION)
STATICCHECK_GOFLAGS ?= -buildvcs=false
COVERAGE_PROFILE ?= coverage.out
COVERAGE_REPORT ?= coverage.txt
COVERAGE_THRESHOLD ?= 85.0
PROJECT_NAME ?= prometheus-ssl-exporter
PROJECT_DESC ?= Prometheus SSL Exporter
FEATURE_NAME ?= ssl
FEATURE_NAMESPACE ?= ssl
METRIC_NAMESPACE ?= ssl_exporter
DEFAULT_PORT ?= :9219
FEATURE_CONFIG_FILE ?= prometheus-ssl-exporter.yml
FEATURE_CONFIG_PATH ?= examples/$(FEATURE_CONFIG_FILE)
FEATURE_CONFIG_CONTAINER_PATH ?= /etc/prometheus/$(FEATURE_CONFIG_FILE)
MAIN_PACKAGE ?= ./cmd
DIST_DIR ?= dist
BUILD_OUTPUT ?= $(DIST_DIR)/$(PROJECT_NAME)
CGO_ENABLED ?= 0
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
BRANCH ?= $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo dev)
REVISION ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo dev)
BUILD_USER ?= $(shell whoami 2>/dev/null || echo unknown)
BUILD_DATE ?= $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
LDFLAGS ?= -s -w \
 -X 'github.com/prometheus/common/version.Version=$(VERSION)' \
 -X 'github.com/prometheus/common/version.Branch=$(BRANCH)' \
 -X 'github.com/prometheus/common/version.Revision=$(REVISION)' \
 -X 'github.com/prometheus/common/version.BuildUser=$(BUILD_USER)' \
 -X 'github.com/prometheus/common/version.BuildDate=$(BUILD_DATE)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedExporterName=$(PROJECT_NAME)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedExporterDescription=$(PROJECT_DESC)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedFeatureName=$(FEATURE_NAME)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedMetricNamespace=$(METRIC_NAMESPACE)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedListenAddress=$(DEFAULT_PORT)' \
 -X '$(GO_MODULE)/internal/$(FEATURE_NAME).DefaultFeatureConfigFileName=$(FEATURE_CONFIG_FILE)'
PLATFORMS ?= linux/amd64 linux/arm64 darwin/amd64 darwin/arm64
IMAGE_TAG ?= $(VERSION)
DOCKER_IMAGE ?= $(PROJECT_NAME):$(IMAGE_TAG)
DOCKER_ENTRYPOINT_NAME ?= exporter
DOCKER_HTTP_IMAGE ?= busybox:1.36
DOCKER_SMOKE_METRIC ?= $(METRIC_NAMESPACE)_last_successful_collection_timestamp_seconds
DOCKER_SMOKE_RUN_OPTIONS ?= -v "$(CURDIR)/$(FEATURE_CONFIG_PATH):$(FEATURE_CONFIG_CONTAINER_PATH):ro"
DOCKER_SMOKE_EXPORTER_ARGS ?= --$(FEATURE_NAME).config-file=$(FEATURE_CONFIG_CONTAINER_PATH)
DOCKER_SMOKE_EXTRA_METRICS ?= 
DOCKER_SMOKE_PORT ?= 9900
DOCKER_SMOKE_EXPECTED_VERSION ?= $(VERSION)
DOCKER_SMOKE_EXPECTED_BRANCH ?= $(BRANCH)
DOCKER_SMOKE_EXPECTED_REVISION ?= $(REVISION)
DOCKER_PLATFORMS ?= linux/amd64,linux/arm64
DOCKER_COMPOSE ?= $(DOCKER) compose
COMPOSE_ARGS ?= up --build
COMPOSE_PROJECT_NAME ?= $(PROJECT_NAME)
COMPOSE_EXPORTER_PORT ?= $(patsubst :%,%,$(DEFAULT_PORT))
PROMETHEUS_IMAGE ?= prom/prometheus:v3.13.1
GRAFANA_IMAGE ?= grafana/grafana:13.0.3
GRAFANA_ADMIN_USER ?= admin
GRAFANA_ADMIN_PASSWORD ?= admin
SMOKE_DOCKER_IMAGE ?= $(PROJECT_NAME):smoke
SMOKE_VERSION ?= v9.8.7
SMOKE_BRANCH ?= smoke-branch
SMOKE_REVISION ?= abc123def
SMOKE_BUILD_USER ?= smoke-test
SMOKE_BUILD_DATE ?= 2026-05-17T00:00:00Z
SMOKE_BINARY ?= $(DIST_DIR)/$(PROJECT_NAME)
SMOKE_LDFLAGS ?= -s -w \
 -X 'github.com/prometheus/common/version.Version=$(SMOKE_VERSION)' \
 -X 'github.com/prometheus/common/version.Branch=$(SMOKE_BRANCH)' \
 -X 'github.com/prometheus/common/version.Revision=$(SMOKE_REVISION)' \
 -X 'github.com/prometheus/common/version.BuildUser=$(SMOKE_BUILD_USER)' \
 -X 'github.com/prometheus/common/version.BuildDate=$(SMOKE_BUILD_DATE)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedExporterName=$(PROJECT_NAME)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedExporterDescription=$(PROJECT_DESC)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedFeatureName=$(FEATURE_NAME)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedMetricNamespace=$(METRIC_NAMESPACE)' \
 -X '$(FRAMEWORK_MODULE)/exporter.injectedListenAddress=$(DEFAULT_PORT)' \
 -X '$(GO_MODULE)/internal/$(FEATURE_NAME).DefaultFeatureConfigFileName=$(FEATURE_CONFIG_FILE)'
